[package]
name = "rescue"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }

diem-config = { workspace = true }
diem-crypto = { workspace = true }
diem-db = { workspace = true }
diem-gas = { workspace = true }
diem-debugger = { workspace = true }
diem-executor = { workspace = true }
diem-logger = { workspace = true }
diem-storage-interface = { workspace = true }
diem-types = { workspace = true }
diem-vm = { workspace = true }
diem-vm-types = { workspace = true }

futures-util = { workspace = true }
handlebars = { workspace = true }
libra-cached-packages = { workspace = true }
libra-smoke-tests = { workspace = true }
libra-framework = { workspace = true }
libra-txs = { workspace = true }
move-compiler = { workspace = true }
move-core-types = { workspace = true }
move-vm-test-utils = { workspace = true }
move-vm-types = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
diem-api-types = { workspace = true }
diem-forge = { workspace = true }
diem-logger = { workspace = true }
diem-temppath = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
smoke-test = { workspace = true }