[package]
name = "OLFramework"
version = "1.0.0"

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
aptos_token = "0x3"
core_resources = "0xA550C18"
vm_reserved = "0x0"
ol_framework = "0x4"
ol_root = "0x0"

[dependencies]
# Using latest rev = "6b610f4" of Aptos CLI Release v1.0.11
# Update "rev" regularly from: https://github.com/aptos-labs/aptos-core/releases
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "6b610f4" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "6b610f4" }
