name: build container

on:
  push:
    branches:
      # make binaries which may be ahead of releases to use in CI jobs
      - "canary*"
      - "ci-bins*"
    tags: # run this also on release candidates
      - "[0-9]+.[0-9]+.[0-9]*"
env:
 BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  publish:
    permissions: write-all
    name: container-build
# Note: builds only Intel container at present
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/libra-node
          tags: |
            # tag as git sha
            type=sha,enable=true,priority=100,prefix=,suffix=,format=long
            # tag canary releases
            type=raw,value=canary,enable=${{contains(env.BRANCH_NAME, 'canary')}}
            # tag ci bins releases
            type=raw,value=ci-bins,enable=${{contains(env.BRANCH_NAME, 'ci-bins')}}
            # tag version
            type=semver,pattern={{version}}



      - name: Log in to Container Image Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./container/Containerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CI_COMMIT_SHA=${{ github.sha }}
