name: publish cli
on:
  push:
    branches:
      # make binaries which may be ahead of releases to use in CI jobs
      - "ci-bins*"
    tags: # run this also on release candidates
      - "[0-9]+.[0-9]+.[0-9]*"

jobs:
  publish:
    permissions: write-all
    name: publish
    runs-on: ubuntu-latest
    steps:
      # NOTE: for debugging CI this allow shell access to github runner. Will print out tmate.io terminal url
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true
      #   timeout-minutes: 15

      - name: checkout
        uses: actions/checkout@v3

      - name: setup env
        uses: ./.github/actions/build_env

      - name: build libra cli release
        # size and performance optimized binary with profile.cli
        run: cargo b --release -p libra

      # CI bin
      - name: libra publish
        if: ${{ contains(github.ref, 'ci-bins') }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/libra
          tag: ci-bins
          overwrite: true
          file_glob: true
