name: publish cli
on:
  push:
    tags: # run this also on release candidates
      - "[0-9]+.[0-9]+.[0-9]*"
    branches:
      - "ci"
jobs:
  publish:
    permissions:
      write-all
      # contents: write
    name: publish
    runs-on: ubuntu-latest
    steps:
      # NOTE: for debugging CI this allow shell access to github runner. Will print out tmate.io terminal url
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   with:
      #     detached: true
      #   timeout-minutes: 15

      - name: checkout
        uses: actions/checkout@v3

      - name: setup env
        uses: ./.github/actions/build_env


      # note: building in the same cargo command will lead to "feature unification", which leads to a `diem-node` binary which fails.
      - name: libra release build
        # size and performance optimized binary with profile.cli
        run: cargo b --release -p libra

      - name: libra publish
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/libra
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
